#############################################################################
# Makefile for building: OpenLive.app/Contents/MacOS/OpenLive
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  OpenLive.pro
# Template: app
# Command: /Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/qmake -o Makefile OpenLive.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib
QMAKE         = /Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OpenLive1.0.0
DISTDIR = /Users/baihe/Projects/sandbox/OpenLive-Windows/.tmp/OpenLive1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		agoraconfig.cpp \
		roomsettings.cpp \
		agoraobject.cpp \
		enterroom.cpp \
		inroom.cpp qrc_openlive.cpp \
		moc_mainwindow.cpp \
		moc_roomsettings.cpp \
		moc_agoraobject.cpp \
		moc_enterroom.cpp \
		moc_inroom.cpp
OBJECTS       = main.o \
		mainwindow.o \
		agoraconfig.o \
		roomsettings.o \
		agoraobject.o \
		enterroom.o \
		inroom.o \
		qrc_openlive.o \
		moc_mainwindow.o \
		moc_roomsettings.o \
		moc_agoraobject.o \
		moc_enterroom.o \
		moc_inroom.o
DIST          = openlive.rc \
		sdk/dll/agora_rtc_sdk.dll \
		sdk/lib/agora_rtc_sdk.lib \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resources_functions.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/lex.prf \
		OpenLive.pro mainwindow.h \
		sdk/include/AgoraBase.h \
		sdk/include/IAgoraLiveEngine.h \
		sdk/include/IAgoraLivePublisher.h \
		sdk/include/IAgoraLiveSubscriber.h \
		sdk/include/IAgoraMediaEngine.h \
		sdk/include/IAgoraRtcEngine.h \
		sdk/include/IAgoraService.h \
		stdafx.h \
		agoraconfig.h \
		roomsettings.h \
		agoraobject.h \
		enterroom.h \
		inroom.h main.cpp \
		mainwindow.cpp \
		agoraconfig.cpp \
		roomsettings.cpp \
		agoraobject.cpp \
		enterroom.cpp \
		inroom.cpp
QMAKE_TARGET  = OpenLive
DESTDIR       = 
TARGET        = OpenLive.app/Contents/MacOS/OpenLive

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/baihe/Projects/sandbox/OpenLive-Windows/OpenLive.pro


include /Users/baihe/Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

OpenLive.app/Contents/MacOS/OpenLive: ui_mainwindow.h ui_roomsettings.h ui_enterroom.h ui_inroom.h $(OBJECTS)  
	@test -d OpenLive.app/Contents/MacOS/ || mkdir -p OpenLive.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpenLive.pro ../../../Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resources_functions.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/lex.prf \
		OpenLive.pro \
		openlive.qrc \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile OpenLive.pro
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/qdevice.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/unix.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/mac.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/macx.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/clang.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/qconfig.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/toolchain.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qt.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resources_functions.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/resources.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/moc.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/uic.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/file_copies.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/lex.prf:
OpenLive.pro:
openlive.qrc:
../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OpenLive.pro

qmake_all: FORCE

OpenLive.app/Contents/PkgInfo: 
	@test -d OpenLive.app/Contents || mkdir -p OpenLive.app/Contents
	@$(DEL_FILE) OpenLive.app/Contents/PkgInfo
	@echo "APPL????" > OpenLive.app/Contents/PkgInfo
OpenLive.app/Contents/Resources/empty.lproj: 
	@test -d OpenLive.app/Contents/Resources || mkdir -p OpenLive.app/Contents/Resources
	@touch OpenLive.app/Contents/Resources/empty.lproj
	
OpenLive.app/Contents/Info.plist: 
	@test -d OpenLive.app/Contents || mkdir -p OpenLive.app/Contents
	@$(DEL_FILE) OpenLive.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.OpenLive,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.OpenLive,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,openlive.rc,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},openlive.rc,g" -e "s,@EXECUTABLE@,OpenLive,g" -e "s,@LIBRARY@,OpenLive,g" -e "s,\$${EXECUTABLE_NAME},OpenLive,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang/Info.plist.app >OpenLive.app/Contents/Info.plist
OpenLive.app/Contents/Resources/openlive.rc: openlive.rc
	@test -d OpenLive.app/Contents/Resources/ || mkdir -p OpenLive.app/Contents/Resources/
	@$(DEL_FILE) OpenLive.app/Contents/Resources/openlive.rc
	@$(COPY_FILE) openlive.rc OpenLive.app/Contents/Resources/openlive.rc

all: Makefile \
		OpenLive.app/Contents/PkgInfo \
		OpenLive.app/Contents/Resources/empty.lproj \
		OpenLive.app/Contents/Info.plist \
		OpenLive.app/Contents/Resources/openlive.rc OpenLive.app/Contents/MacOS/OpenLive

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents openlive.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h sdk/include/AgoraBase.h sdk/include/IAgoraLiveEngine.h sdk/include/IAgoraLivePublisher.h sdk/include/IAgoraLiveSubscriber.h sdk/include/IAgoraMediaEngine.h sdk/include/IAgoraRtcEngine.h sdk/include/IAgoraService.h stdafx.h agoraconfig.h roomsettings.h agoraobject.h enterroom.h inroom.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp agoraconfig.cpp roomsettings.cpp agoraobject.cpp enterroom.cpp inroom.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui roomsettings.ui enterroom.ui inroom.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r OpenLive.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_openlive.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_openlive.cpp
qrc_openlive.cpp: openlive.qrc \
		../../../Qt5.14.1/5.14.1/clang_64/bin/rcc \
		uiresource/box-01.png \
		uiresource/Open\ live-03.jpg \
		uiresource/Groupparam.png \
		uiresource/icon-microphone\ hover.png \
		uiresource/pic-guide\ 01.png \
		uiresource/dropdow-01.png \
		uiresource/mutevideo\ remote.png \
		uiresource/close-hover.png \
		uiresource/icon-back.png \
		uiresource/Group\ 31.png \
		uiresource/icon-camera\ off.png \
		uiresource/button-default.png \
		uiresource/radio_checked.png \
		uiresource/close-pushed.png \
		uiresource/icon-exit.png \
		uiresource/close-normal.png \
		uiresource/pic-live\ 02.png \
		uiresource/count.png \
		uiresource/icon-camera.png \
		uiresource/allmute\ remote.png \
		uiresource/radio_unchecked.png \
		uiresource/pic-win03.png \
		uiresource/allmute.png \
		uiresource/slider.png \
		uiresource/normal.png \
		uiresource/icon-camera\ off\ hover.png \
		uiresource/switch-open.png \
		uiresource/icon-microphone\ off.png \
		uiresource/icon-exit\ hover.png \
		uiresource/icon-back\ hover.png \
		uiresource/dropdown-03.png \
		uiresource/pic-win01.png \
		uiresource/icon-setting\ hover.png \
		uiresource/button-hover.png \
		uiresource/white.png \
		uiresource/list.png \
		uiresource/icon-setting.png \
		uiresource/dropdown-02.png \
		uiresource/min-hover.png \
		uiresource/icon-microphone.png \
		uiresource/pic-live01.png \
		uiresource/switch-off.png \
		uiresource/remoteuid.png \
		uiresource/channel_name_edittext.png \
		uiresource/icon-microphone\ off\ hover.png \
		uiresource/box-03.png \
		uiresource/page_settings.png \
		uiresource/mutevideo.png \
		uiresource/box-02.png \
		uiresource/min-pushed.png \
		uiresource/pic-guide\ 02.png \
		uiresource/min-normal.png \
		uiresource/icon-camera\ hover.png
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/rcc -name openlive openlive.qrc -o qrc_openlive.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h ../../../Qt5.14.1/5.14.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_roomsettings.cpp moc_agoraobject.cpp moc_enterroom.cpp moc_inroom.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_roomsettings.cpp moc_agoraobject.cpp moc_enterroom.cpp moc_inroom.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		roomsettings.h \
		mainwindow.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		../../../Qt5.14.1/5.14.1/clang_64/bin/moc
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/moc $(DEFINES) --include /Users/baihe/Projects/sandbox/OpenLive-Windows/moc_predefs.h -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang -I/Users/baihe/Projects/sandbox/OpenLive-Windows -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_roomsettings.cpp: roomsettings.h \
		mainwindow.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		roomsettings.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		../../../Qt5.14.1/5.14.1/clang_64/bin/moc
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/moc $(DEFINES) --include /Users/baihe/Projects/sandbox/OpenLive-Windows/moc_predefs.h -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang -I/Users/baihe/Projects/sandbox/OpenLive-Windows -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib roomsettings.h -o moc_roomsettings.cpp

moc_agoraobject.cpp: agoraobject.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		moc_predefs.h \
		../../../Qt5.14.1/5.14.1/clang_64/bin/moc
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/moc $(DEFINES) --include /Users/baihe/Projects/sandbox/OpenLive-Windows/moc_predefs.h -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang -I/Users/baihe/Projects/sandbox/OpenLive-Windows -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib agoraobject.h -o moc_agoraobject.cpp

moc_enterroom.cpp: enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../../../Qt5.14.1/5.14.1/clang_64/bin/moc
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/moc $(DEFINES) --include /Users/baihe/Projects/sandbox/OpenLive-Windows/moc_predefs.h -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang -I/Users/baihe/Projects/sandbox/OpenLive-Windows -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib enterroom.h -o moc_enterroom.cpp

moc_inroom.cpp: inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		../../../Qt5.14.1/5.14.1/clang_64/bin/moc
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/moc $(DEFINES) --include /Users/baihe/Projects/sandbox/OpenLive-Windows/moc_predefs.h -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/mkspecs/macx-clang -I/Users/baihe/Projects/sandbox/OpenLive-Windows -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers -I/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/baihe/Qt5.14.1/5.14.1/clang_64/lib inroom.h -o moc_inroom.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_roomsettings.h ui_enterroom.h ui_inroom.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_roomsettings.h ui_enterroom.h ui_inroom.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt5.14.1/5.14.1/clang_64/bin/uic
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_roomsettings.h: roomsettings.ui \
		../../../Qt5.14.1/5.14.1/clang_64/bin/uic
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/uic roomsettings.ui -o ui_roomsettings.h

ui_enterroom.h: enterroom.ui \
		../../../Qt5.14.1/5.14.1/clang_64/bin/uic
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/uic enterroom.ui -o ui_enterroom.h

ui_inroom.h: inroom.ui \
		../../../Qt5.14.1/5.14.1/clang_64/bin/uic
	/Users/baihe/Qt5.14.1/5.14.1/clang_64/bin/uic inroom.ui -o ui_inroom.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp stdafx.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		agoraconfig.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		mainwindow.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		roomsettings.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp stdafx.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		agoraconfig.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		mainwindow.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		roomsettings.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui_mainwindow.h \
		agoraobject.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

agoraconfig.o: agoraconfig.cpp stdafx.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		agoraconfig.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agoraconfig.o agoraconfig.cpp

roomsettings.o: roomsettings.cpp stdafx.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		agoraconfig.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		roomsettings.h \
		mainwindow.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui_roomsettings.h \
		agoraobject.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o roomsettings.o roomsettings.cpp

agoraobject.o: agoraobject.cpp agoraobject.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agoraobject.o agoraobject.cpp

enterroom.o: enterroom.cpp stdafx.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		agoraconfig.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_enterroom.h \
		agoraobject.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enterroom.o enterroom.cpp

inroom.o: inroom.cpp stdafx.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		agoraconfig.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QSettings \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		agoraobject.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		inroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		enterroom.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt5.14.1/5.14.1/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		ui_inroom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inroom.o inroom.cpp

qrc_openlive.o: qrc_openlive.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_openlive.o qrc_openlive.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_roomsettings.o: moc_roomsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_roomsettings.o moc_roomsettings.cpp

moc_agoraobject.o: moc_agoraobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_agoraobject.o moc_agoraobject.cpp

moc_enterroom.o: moc_enterroom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enterroom.o moc_enterroom.cpp

moc_inroom.o: moc_inroom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inroom.o moc_inroom.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

